modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="eternal_spells"
version="1.0.0"
displayName="Eternal Spells"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="gabes, MCreator"

[[dependencies.eternal_spells]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




